<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CctvSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cctvData = [
            // Asset - Online
            [
                'nama_perangkat' => 'CCTV Entrance Gate A',
                'ip_address' => '192.168.1.101',
                'tanggal_pencatatan' => Carbon::now()->subDays(30),
                'kepemilikan' => 'asset',
                'status' => 'online',
                'up' => '15d 10h 30m 15s',
                'down' => '45m 20s',
                'availability' => '99.789',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Parking Area',
                'ip_address' => '192.168.1.102',
                'tanggal_pencatatan' => Carbon::now()->subDays(25),
                'kepemilikan' => 'asset',
                'status' => 'online',
                'up' => '20d 5h 15m 40s',
                'down' => '30m 10s',
                'availability' => '99.895',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(25),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Main Lobby',
                'ip_address' => '192.168.1.103',
                'tanggal_pencatatan' => Carbon::now()->subDays(28),
                'kepemilikan' => 'asset',
                'status' => 'online',
                'up' => '6d 22h 45m 6s',
                'down' => '14m 54s',
                'availability' => '99.851',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(28),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Server Room',
                'ip_address' => '192.168.1.104',
                'tanggal_pencatatan' => Carbon::now()->subDays(35),
                'kepemilikan' => 'asset',
                'status' => 'online',
                'up' => '30d 15h 20m 30s',
                'down' => '10m 5s',
                'availability' => '99.978',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(35),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Storage Area',
                'ip_address' => '192.168.1.105',
                'tanggal_pencatatan' => Carbon::now()->subDays(20),
                'kepemilikan' => 'asset',
                'status' => 'online',
                'up' => '18d 8h 35m 12s',
                'down' => '25m 30s',
                'availability' => '99.901',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(20),
                'updated_at' => Carbon::now(),
            ],

            // Asset - Offline
            [
                'nama_perangkat' => 'CCTV Back Door',
                'ip_address' => '192.168.1.106',
                'tanggal_pencatatan' => Carbon::now()->subDays(40),
                'kepemilikan' => 'asset',
                'status' => 'offline',
                'up' => '0d 0h 0m 0s',
                'down' => '40d 0h 0m 0s',
                'availability' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(40),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'nama_perangkat' => 'CCTV Emergency Exit',
                'ip_address' => '192.168.1.107',
                'tanggal_pencatatan' => Carbon::now()->subDays(33),
                'kepemilikan' => 'asset',
                'status' => 'offline',
                'up' => '0d 0h 0m 0s',
                'down' => '33d 0h 0m 0s',
                'availability' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(33),
                'updated_at' => Carbon::now()->subDays(1),
            ],

            // Sewa - Online
            [
                'nama_perangkat' => 'CCTV Perimeter North',
                'ip_address' => '192.168.2.101',
                'tanggal_pencatatan' => Carbon::now()->subDays(15),
                'kepemilikan' => 'sewa',
                'status' => 'online',
                'up' => '12d 18h 25m 45s',
                'down' => '20m 15s',
                'availability' => '99.912',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(15),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Perimeter South',
                'ip_address' => '192.168.2.102',
                'tanggal_pencatatan' => Carbon::now()->subDays(15),
                'kepemilikan' => 'sewa',
                'status' => 'online',
                'up' => '14d 8h 50m 30s',
                'down' => '18m 40s',
                'availability' => '99.925',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(15),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Loading Dock',
                'ip_address' => '192.168.2.103',
                'tanggal_pencatatan' => Carbon::now()->subDays(10),
                'kepemilikan' => 'sewa',
                'status' => 'online',
                'up' => '9d 15h 40m 20s',
                'down' => '35m 50s',
                'availability' => '99.745',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(10),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Warehouse 1',
                'ip_address' => '192.168.2.104',
                'tanggal_pencatatan' => Carbon::now()->subDays(12),
                'kepemilikan' => 'sewa',
                'status' => 'online',
                'up' => '11d 20h 15m 55s',
                'down' => '22m 5s',
                'availability' => '99.890',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(12),
                'updated_at' => Carbon::now(),
            ],

            // Sewa - Offline
            [
                'nama_perangkat' => 'CCTV Warehouse 2',
                'ip_address' => '192.168.2.105',
                'tanggal_pencatatan' => Carbon::now()->subDays(18),
                'kepemilikan' => 'sewa',
                'status' => 'offline',
                'up' => '0d 0h 0m 0s',
                'down' => '18d 0h 0m 0s',
                'availability' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(18),
                'updated_at' => Carbon::now()->subHours(5),
            ],
            [
                'nama_perangkat' => 'CCTV Guard Post',
                'ip_address' => '192.168.2.106',
                'tanggal_pencatatan' => Carbon::now()->subDays(22),
                'kepemilikan' => 'sewa',
                'status' => 'offline',
                'up' => '0d 0h 0m 0s',
                'down' => '22d 0h 0m 0s',
                'availability' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(22),
                'updated_at' => Carbon::now()->subHours(12),
            ],

            // Additional CCTVs for more variety
            [
                'nama_perangkat' => 'CCTV Office Floor 1',
                'ip_address' => '192.168.1.108',
                'tanggal_pencatatan' => Carbon::now()->subDays(45),
                'kepemilikan' => 'asset',
                'status' => 'online',
                'up' => '40d 12h 15m 20s',
                'down' => '8m 40s',
                'availability' => '99.989',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(45),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Office Floor 2',
                'ip_address' => '192.168.1.109',
                'tanggal_pencatatan' => Carbon::now()->subDays(45),
                'kepemilikan' => 'asset',
                'status' => 'online',
                'up' => '42d 8h 30m 50s',
                'down' => '12m 10s',
                'availability' => '99.967',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(45),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Cafeteria',
                'ip_address' => '192.168.1.110',
                'tanggal_pencatatan' => Carbon::now()->subDays(38),
                'kepemilikan' => 'asset',
                'status' => 'online',
                'up' => '35d 16h 40m 25s',
                'down' => '15m 35s',
                'availability' => '99.945',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(38),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Meeting Room',
                'ip_address' => '192.168.1.111',
                'tanggal_pencatatan' => Carbon::now()->subDays(42),
                'kepemilikan' => 'asset',
                'status' => 'offline',
                'up' => '0d 0h 0m 0s',
                'down' => '42d 0h 0m 0s',
                'availability' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(42),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'nama_perangkat' => 'CCTV Corridor East',
                'ip_address' => '192.168.2.107',
                'tanggal_pencatatan' => Carbon::now()->subDays(8),
                'kepemilikan' => 'sewa',
                'status' => 'online',
                'up' => '7d 20h 50m 35s',
                'down' => '28m 25s',
                'availability' => '99.812',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(8),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'CCTV Corridor West',
                'ip_address' => '192.168.2.108',
                'tanggal_pencatatan' => Carbon::now()->subDays(8),
                'kepemilikan' => 'sewa',
                'status' => 'online',
                'up' => '7d 18h 35m 40s',
                'down' => '32m 20s',
                'availability' => '99.765',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(8),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('cctv')->insert($cctvData);
    }
}
