<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class NetworkDeviceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $networkDevices = [
            // Switches
            [
                'nama_perangkat' => 'Core Switch - Main Building',
                'ip_address' => '192.168.10.1',
                'tanggal_pencatatan' => Carbon::now()->subDays(60),
                'jenis' => 'switch',
                'up' => '58d 10h 25m 30s',
                'down' => '8m 15s',
                'availability' => '99.991',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(60),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'Distribution Switch - Floor 1',
                'ip_address' => '192.168.10.11',
                'tanggal_pencatatan' => Carbon::now()->subDays(45),
                'jenis' => 'switch',
                'up' => '43d 18h 40m 20s',
                'down' => '12m 30s',
                'availability' => '99.980',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(45),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'Distribution Switch - Floor 2',
                'ip_address' => '192.168.10.12',
                'tanggal_pencatatan' => Carbon::now()->subDays(45),
                'jenis' => 'switch',
                'up' => '44d 5h 15m 45s',
                'down' => '10m 20s',
                'availability' => '99.984',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(45),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'Access Switch - Server Room',
                'ip_address' => '192.168.10.21',
                'tanggal_pencatatan' => Carbon::now()->subDays(30),
                'jenis' => 'switch',
                'up' => '29d 20h 30m 10s',
                'down' => '15m 50s',
                'availability' => '99.963',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'Access Switch - Office Area',
                'ip_address' => '192.168.10.22',
                'tanggal_pencatatan' => Carbon::now()->subDays(30),
                'jenis' => 'switch',
                'up' => '28d 12h 45m 30s',
                'down' => '25m 15s',
                'availability' => '99.942',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(30),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'Access Switch - Warehouse',
                'ip_address' => '192.168.10.23',
                'tanggal_pencatatan' => Carbon::now()->subDays(35),
                'jenis' => 'switch',
                'up' => '0d 0h 0m 0s',
                'down' => '35d 0h 0m 0s',
                'availability' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(35),
                'updated_at' => Carbon::now()->subDays(5),
            ],

            // Access Points
            [
                'nama_perangkat' => 'AP - Main Lobby',
                'ip_address' => '192.168.20.1',
                'tanggal_pencatatan' => Carbon::now()->subDays(40),
                'jenis' => 'access point',
                'up' => '38d 15h 20m 40s',
                'down' => '18m 25s',
                'availability' => '99.968',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(40),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'AP - Office Floor 1',
                'ip_address' => '192.168.20.11',
                'tanggal_pencatatan' => Carbon::now()->subDays(35),
                'jenis' => 'access point',
                'up' => '34d 10h 35m 15s',
                'down' => '20m 45s',
                'availability' => '99.958',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(35),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'AP - Office Floor 2',
                'ip_address' => '192.168.20.12',
                'tanggal_pencatatan' => Carbon::now()->subDays(35),
                'jenis' => 'access point',
                'up' => '33d 8h 50m 30s',
                'down' => '22m 10s',
                'availability' => '99.955',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(35),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'AP - Meeting Room A',
                'ip_address' => '192.168.20.21',
                'tanggal_pencatatan' => Carbon::now()->subDays(28),
                'jenis' => 'access point',
                'up' => '27d 18h 25m 50s',
                'down' => '28m 10s',
                'availability' => '99.930',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(28),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'AP - Meeting Room B',
                'ip_address' => '192.168.20.22',
                'tanggal_pencatatan' => Carbon::now()->subDays(28),
                'jenis' => 'access point',
                'up' => '26d 20h 40m 15s',
                'down' => '30m 45s',
                'availability' => '99.920',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(28),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'AP - Cafeteria',
                'ip_address' => '192.168.20.31',
                'tanggal_pencatatan' => Carbon::now()->subDays(25),
                'jenis' => 'access point',
                'up' => '24d 15h 30m 20s',
                'down' => '35m 40s',
                'availability' => '99.900',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(25),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'AP - Parking Area',
                'ip_address' => '192.168.20.41',
                'tanggal_pencatatan' => Carbon::now()->subDays(20),
                'jenis' => 'access point',
                'up' => '0d 0h 0m 0s',
                'down' => '20d 0h 0m 0s',
                'availability' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(20),
                'updated_at' => Carbon::now()->subDays(3),
            ],

            // Network Devices (Routers, Firewalls, etc.)
            [
                'nama_perangkat' => 'Main Gateway Router',
                'ip_address' => '192.168.1.1',
                'tanggal_pencatatan' => Carbon::now()->subDays(90),
                'jenis' => 'network',
                'up' => '88d 18h 45m 30s',
                'down' => '5m 30s',
                'availability' => '99.996',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(90),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'Firewall - Primary',
                'ip_address' => '192.168.1.2',
                'tanggal_pencatatan' => Carbon::now()->subDays(90),
                'jenis' => 'network',
                'up' => '89d 5h 20m 15s',
                'down' => '4m 45s',
                'availability' => '99.997',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(90),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'Load Balancer',
                'ip_address' => '192.168.1.10',
                'tanggal_pencatatan' => Carbon::now()->subDays(60),
                'jenis' => 'network',
                'up' => '59d 12h 30m 45s',
                'down' => '10m 15s',
                'availability' => '99.988',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(60),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'VPN Gateway',
                'ip_address' => '192.168.1.20',
                'tanggal_pencatatan' => Carbon::now()->subDays(50),
                'jenis' => 'network',
                'up' => '48d 20h 15m 30s',
                'down' => '15m 30s',
                'availability' => '99.978',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(50),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'Network Monitor Server',
                'ip_address' => '192.168.1.30',
                'tanggal_pencatatan' => Carbon::now()->subDays(45),
                'jenis' => 'network',
                'up' => '44d 8h 40m 20s',
                'down' => '20m 40s',
                'availability' => '99.968',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(45),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_perangkat' => 'Backup Router',
                'ip_address' => '192.168.1.254',
                'tanggal_pencatatan' => Carbon::now()->subDays(40),
                'jenis' => 'network',
                'up' => '0d 0h 0m 0s',
                'down' => '40d 0h 0m 0s',
                'availability' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => Carbon::now()->subDays(40),
                'updated_at' => Carbon::now()->subDays(7),
            ],
        ];

        DB::table('networkdevice')->insert($networkDevices);
    }
}
